# Generated by Django 4.2 on 2023-05-03 09:17

import datetime
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='brand/')),
            ],
            options={
                'db_table': 'Brand',
            },
        ),
        migrations.CreateModel(
            name='CarEngineAndTransmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Engine_Type', models.CharField(max_length=100)),
                ('Engine_Displacement', models.IntegerField()),
                ('No_Of_Cylinder', models.IntegerField()),
                ('Max_Power', models.CharField()),
                ('Torque', models.CharField()),
                ('Transmission_Type', models.CharField(max_length=100)),
                ('Drive_Type', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'CarEngine And Transmission',
            },
        ),
        migrations.CreateModel(
            name='CarType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'CarType',
            },
        ),
        migrations.CreateModel(
            name='CarVarient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'CarVarient',
            },
        ),
        migrations.CreateModel(
            name='Exterior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rims', models.CharField(max_length=100)),
                ('Color', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Exterior',
            },
        ),
        migrations.CreateModel(
            name='Fuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FuelType', models.CharField(max_length=100)),
                ('TankCapacity', models.FloatField()),
                ('TopSpeed', models.IntegerField()),
                ('Mileage', models.FloatField()),
            ],
            options={
                'db_table': 'Fuel',
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('comfort', multiselectfield.db.fields.MultiSelectField(choices=[('Vanity Mirror', 'Vanity Mirror'), ('Fog Lights - Front', 'Fog Lights - Front'), ('Adjustable seats', 'Adjustable seats'), ('Air Conditioning', 'Air Conditioning'), ('Seat Heating', 'Seat Heating'), ('Alarm System', 'Alarm System'), ('Park Assist', 'Park Assist'), ('Power Steering', 'Power Steering'), ('Reversing Camera', 'Reversing Camera'), ('Direct Fuel Injection', 'Direct Fuel Injection'), ('Auto Start/Stop', 'Auto Start/Stop'), ('Blind Spot Monitor', 'Blind Spot Monitor'), ('Bluetooth Handset', 'Bluetooth Handset')], max_length=2000)),
                ('capacity', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=10)),
                ('year', models.IntegerField(choices=[(2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025), (2026, 2026)], verbose_name='year')),
                ('is_featured', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(default=datetime.datetime.now)),
                ('image1', models.ImageField(upload_to='car/')),
                ('image2', models.ImageField(upload_to='car/')),
                ('image3', models.ImageField(upload_to='car/')),
                ('Engine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.carengineandtransmission')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.brand')),
                ('cartype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.cartype')),
                ('carvarient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.carvarient')),
                ('exterior', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.exterior')),
                ('fuel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.fuel')),
            ],
            options={
                'db_table': 'car',
            },
        ),
    ]
